<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/JevMud.Adapters/JevMud.Adapters.csproj" />
    <ProjectReference Include="../../src/JevMud.Client/JevMud.Client.csproj" />
    <ProjectReference Include="../../src/JevMud.Contracts/JevMud.Contracts.csproj" />
    <ProjectReference Include="../../src/JevMud.Core/JevMud.Core.csproj" />
    <ProjectReference Include="../../src/JevMud.Gui/JevMud.Gui.csproj" />
    <ProjectReference Include="../../src/JevMud.Transport/JevMud.Transport.csproj" />
    <ProjectReference Include="../../src/JevMud.Jev/JevMud.Jev.csproj" />
    <ProjectReference Include="../../src/JevMud.Scripting/JevMud.Scripting.csproj" />
    <ProjectReference Include="../../src/JevMud.Scripting.Jint/JevMud.Scripting.Jint.csproj" />
    <ProjectReference Include="../../src/JevMud.Scripting.TypeScript/JevMud.Scripting.TypeScript.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures/**/*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
