<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../JevMud.Contracts/JevMud.Contracts.csproj" />
    <ProjectReference Include="../JevMud.Core/JevMud.Core.csproj" />
    <ProjectReference Include="../JevMud.Transport/JevMud.Transport.csproj" />
  </ItemGroup>
</Project>
