using JevMud.Contracts.Jev;

namespace JevMud.Client.Settings;

public sealed record ClientSettings(
    JevPreset JevPreset,
    Dictionary<JevDomain, JevAuthority> JevDomains,
    string Host,
    int Port,
    bool UseTls,
    string TerminalType = "xterm-256color",
    double TranscriptFontSize = 11,
    bool ShowContextDock = true,
    bool AutoOpenCombatContext = true,
    string JevModel = "jev-latest",
    bool AutoLogSessions = false,
    bool SlurpTelemetryPrompt = false,
    IReadOnlyList<TranscriptHighlightRule>? HighlightRules = null,
    TranscriptLogFormat LogFormat = TranscriptLogFormat.AnsiText,
    IReadOnlyList<CommandAlias>? Aliases = null,
    IReadOnlyList<TriggerRule>? Triggers = null,
    IReadOnlyList<GameRule>? GameRules = null,
    IReadOnlyList<AutomationWorkflow>? Workflows = null,
    IReadOnlyList<CommandTimer>? Timers = null,
    IReadOnlyList<CommandKeyBinding>? KeyBindings = null,
    WorkspacePreferences? Workspace = null,
    AutomationPreferences? Automation = null,
    ProtocolPreferences? Protocols = null,
    MapperPreferences? Mapper = null,
    bool JevEnabled = true,
    string CommandSeparator = ";")
{
    public static ClientSettings Default { get; } = new(
        JevPreset.Off,
        Enum.GetValues<JevDomain>().ToDictionary(domain => domain, _ => JevAuthority.Off),
        "avendar.net",
        9999,
        false,
        "xterm-256color",
        11,
        true,
        true,
        "jev-latest",
        false,
        false,
        [],
        TranscriptLogFormat.AnsiText,
        [],
        [],
        [],
        [],
        [],
        [],
        new WorkspacePreferences(),
        new AutomationPreferences(),
        new ProtocolPreferences(),
        new MapperPreferences(),
        true,
        ";");
}
